@echo off
setlocal EnableExtensions
cd /d "%~dp0\.."

echo === Renaming project files to .txt ===
echo Working dir: %CD%
echo.

set OK=0
set MISSING=0

if exist ".eslintrc.cjs"                                                          (ren ".eslintrc.cjs"                                                          ".eslintrc.cjs.txt"          & set /a OK+=1 & echo [OK]      .eslintrc.cjs)                                                          else (set /a MISSING+=1 & echo [MISSING] .eslintrc.cjs)
if exist ".gitignore"                                                             (ren ".gitignore"                                                             ".gitignore.txt"             & set /a OK+=1 & echo [OK]      .gitignore)                                                             else (set /a MISSING+=1 & echo [MISSING] .gitignore)
if exist "eslint.config.cjs"                                                      (ren "eslint.config.cjs"                                                      "eslint.config.cjs.txt"      & set /a OK+=1 & echo [OK]      eslint.config.cjs)                                                      else (set /a MISSING+=1 & echo [MISSING] eslint.config.cjs)
if exist "IMPROVEMENTS.md"                                                        (ren "IMPROVEMENTS.md"                                                        "IMPROVEMENTS.md.txt"        & set /a OK+=1 & echo [OK]      IMPROVEMENTS.md)                                                        else (set /a MISSING+=1 & echo [MISSING] IMPROVEMENTS.md)
if exist "index.html"                                                             (ren "index.html"                                                             "index.html.txt"             & set /a OK+=1 & echo [OK]      index.html)                                                             else (set /a MISSING+=1 & echo [MISSING] index.html)
if exist "package.json"                                                           (ren "package.json"                                                           "package.json.txt"           & set /a OK+=1 & echo [OK]      package.json)                                                           else (set /a MISSING+=1 & echo [MISSING] package.json)
if exist "package-lock.json"                                                      (ren "package-lock.json"                                                      "package-lock.json.txt"      & set /a OK+=1 & echo [OK]      package-lock.json)                                                      else (set /a MISSING+=1 & echo [MISSING] package-lock.json)
if exist "public\robots.txt"                                                      (ren "public\robots.txt"                                                      "robots.txt.txt"             & set /a OK+=1 & echo [OK]      public\robots.txt)                                                      else (set /a MISSING+=1 & echo [MISSING] public\robots.txt)
if exist "README.md"                                                              (ren "README.md"                                                              "README.md.txt"              & set /a OK+=1 & echo [OK]      README.md)                                                              else (set /a MISSING+=1 & echo [MISSING] README.md)
if exist "REQUIREMENTS.md"                                                        (ren "REQUIREMENTS.md"                                                        "REQUIREMENTS.md.txt"        & set /a OK+=1 & echo [OK]      REQUIREMENTS.md)                                                        else (set /a MISSING+=1 & echo [MISSING] REQUIREMENTS.md)
if exist "tsconfig.json"                                                          (ren "tsconfig.json"                                                          "tsconfig.json.txt"          & set /a OK+=1 & echo [OK]      tsconfig.json)                                                          else (set /a MISSING+=1 & echo [MISSING] tsconfig.json)
if exist "vite.config.ts"                                                         (ren "vite.config.ts"                                                         "vite.config.ts.txt"         & set /a OK+=1 & echo [OK]      vite.config.ts)                                                         else (set /a MISSING+=1 & echo [MISSING] vite.config.ts)
if exist "src\env.d.ts"                                                           (ren "src\env.d.ts"                                                           "env.d.ts.txt"               & set /a OK+=1 & echo [OK]      src\env.d.ts)                                                           else (set /a MISSING+=1 & echo [MISSING] src\env.d.ts)
if exist "src\main.ts"                                                            (ren "src\main.ts"                                                            "main.ts.txt"                & set /a OK+=1 & echo [OK]      src\main.ts)                                                            else (set /a MISSING+=1 & echo [MISSING] src\main.ts)
if exist "src\vite-env.d.ts"                                                      (ren "src\vite-env.d.ts"                                                      "vite-env.d.ts.txt"          & set /a OK+=1 & echo [OK]      src\vite-env.d.ts)                                                      else (set /a MISSING+=1 & echo [MISSING] src\vite-env.d.ts)
if exist "src\App\style.sass"                                                     (ren "src\App\style.sass"                                                     "style.sass.txt"             & set /a OK+=1 & echo [OK]      src\App\style.sass)                                                     else (set /a MISSING+=1 & echo [MISSING] src\App\style.sass)
if exist "src\App\__tests__\index.a11y.test.ts"                                  (ren "src\App\__tests__\index.a11y.test.ts"                                   "index.a11y.test.ts.txt"     & set /a OK+=1 & echo [OK]      src\App\__tests__\index.a11y.test.ts)                                  else (set /a MISSING+=1 & echo [MISSING] src\App\__tests__\index.a11y.test.ts)
if exist "src\components\Form\index.html"                                         (ren "src\components\Form\index.html"                                         "index.html.txt"             & set /a OK+=1 & echo [OK]      src\components\Form\index.html)                                         else (set /a MISSING+=1 & echo [MISSING] src\components\Form\index.html)
if exist "src\components\Form\index.ts"                                           (ren "src\components\Form\index.ts"                                           "index.ts.txt"               & set /a OK+=1 & echo [OK]      src\components\Form\index.ts)                                           else (set /a MISSING+=1 & echo [MISSING] src\components\Form\index.ts)
if exist "src\components\Form\style.sass"                                         (ren "src\components\Form\style.sass"                                         "style.sass.txt"             & set /a OK+=1 & echo [OK]      src\components\Form\style.sass)                                         else (set /a MISSING+=1 & echo [MISSING] src\components\Form\style.sass)
if exist "src\components\Form\__tests__\index.a11y.test.ts"                      (ren "src\components\Form\__tests__\index.a11y.test.ts"                       "index.a11y.test.ts.txt"     & set /a OK+=1 & echo [OK]      src\components\Form\__tests__\index.a11y.test.ts)                      else (set /a MISSING+=1 & echo [MISSING] src\components\Form\__tests__\index.a11y.test.ts)
if exist "src\components\SubmissionList\index.html"                               (ren "src\components\SubmissionList\index.html"                               "index.html.txt"             & set /a OK+=1 & echo [OK]      src\components\SubmissionList\index.html)                               else (set /a MISSING+=1 & echo [MISSING] src\components\SubmissionList\index.html)
if exist "src\components\SubmissionList\index.ts"                                 (ren "src\components\SubmissionList\index.ts"                                 "index.ts.txt"               & set /a OK+=1 & echo [OK]      src\components\SubmissionList\index.ts)                                 else (set /a MISSING+=1 & echo [MISSING] src\components\SubmissionList\index.ts)
if exist "src\components\SubmissionList\style.sass"                               (ren "src\components\SubmissionList\style.sass"                               "style.sass.txt"             & set /a OK+=1 & echo [OK]      src\components\SubmissionList\style.sass)                               else (set /a MISSING+=1 & echo [MISSING] src\components\SubmissionList\style.sass)
if exist "src\components\SubmissionList\__tests__\index.a11y.test.ts"            (ren "src\components\SubmissionList\__tests__\index.a11y.test.ts"             "index.a11y.test.ts.txt"     & set /a OK+=1 & echo [OK]      src\components\SubmissionList\__tests__\index.a11y.test.ts)            else (set /a MISSING+=1 & echo [MISSING] src\components\SubmissionList\__tests__\index.a11y.test.ts)
if exist "src\components\SubmissionList\__tests__\index.test.ts"                 (ren "src\components\SubmissionList\__tests__\index.test.ts"                  "index.test.ts.txt"          & set /a OK+=1 & echo [OK]      src\components\SubmissionList\__tests__\index.test.ts)                 else (set /a MISSING+=1 & echo [MISSING] src\components\SubmissionList\__tests__\index.test.ts)
if exist "src\styles\theme.sass"                                                  (ren "src\styles\theme.sass"                                                  "theme.sass.txt"             & set /a OK+=1 & echo [OK]      src\styles\theme.sass)                                                  else (set /a MISSING+=1 & echo [MISSING] src\styles\theme.sass)
if exist "src\test-setup\a11y.ts"                                                 (ren "src\test-setup\a11y.ts"                                                 "a11y.ts.txt"                & set /a OK+=1 & echo [OK]      src\test-setup\a11y.ts)                                                 else (set /a MISSING+=1 & echo [MISSING] src\test-setup\a11y.ts)
if exist "src\test-setup\fixtures.ts"                                             (ren "src\test-setup\fixtures.ts"                                             "fixtures.ts.txt"            & set /a OK+=1 & echo [OK]      src\test-setup\fixtures.ts)                                             else (set /a MISSING+=1 & echo [MISSING] src\test-setup\fixtures.ts)
if exist "src\test-setup\vitest-axe.d.ts"                                        (ren "src\test-setup\vitest-axe.d.ts"                                         "vitest-axe.d.ts.txt"        & set /a OK+=1 & echo [OK]      src\test-setup\vitest-axe.d.ts)                                        else (set /a MISSING+=1 & echo [MISSING] src\test-setup\vitest-axe.d.ts)
if exist "src\utils\validation.ts"                                                (ren "src\utils\validation.ts"                                                "validation.ts.txt"          & set /a OK+=1 & echo [OK]      src\utils\validation.ts)                                                else (set /a MISSING+=1 & echo [MISSING] src\utils\validation.ts)
if exist "src\utils\__tests__\validation.test.ts"                                (ren "src\utils\__tests__\validation.test.ts"                                 "validation.test.ts.txt"     & set /a OK+=1 & echo [OK]      src\utils\__tests__\validation.test.ts)                                else (set /a MISSING+=1 & echo [MISSING] src\utils\__tests__\validation.test.ts)

echo.
echo Renamed : %OK%
echo Missing : %MISSING%
echo.
pause
exit /b 0
